app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from app import views as vistas


urlpatterns = [
    path('conferencias/', vistas.conferencias, name = 'conferencias'),
    path('conferencia/', vistas.conferencia_view, name = "conferencia_view"),
    path('blogs/', vistas.blog_list, name = "blog_list"),
    path('blog/', vistas.blog_view, name = "blog"),
    path('contacto/', vistas.contacto, name = "contacto"),

 ]

avivabajio/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from avivabajio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('', include(('app.urls', 'app'), namespace='app' )),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'AvivaBajío'

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from bases import views as vistas
from bases.views import  HomeSinPrivilegios


urlpatterns = [
    path('', vistas.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login-2.html'),
                name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login-2.html'),
                name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),

]

app/models.py
from django.db import models

# Create your models here.

bases/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render


def conferencias(request):

    return render(request, 'app/conferencias_list.html')


def conferencia_view(request):

    return render(request, 'app/conferencia.html')


def blog_list(request):

    return render(request, 'app/blog_list.html')


def blog_view(request):

    return render(request, 'app/blog.html')

def contacto(request):

    return render(request, 'app/contact.html')

bases/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


# class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin):

#     login_url = "bases:login"
#     raise_exception = False
#     redirect_field_name = "redirect_to"

#     def handle_no_permission(self):
#         from django.contrib.auth.models import AnonymousUser
#         if not self.request.user == AnonymousUser():
#             self.login_url = 'bases:sin_privilegios'
#         return HttpResponseRedirect(reverse_lazy(self.login_url))


class HomeSinPrivilegios(LoginRequiredMixin, generic.TemplateView):
    login_url = "bases:login"
    template_name = "bases/sin_privilegios.html"

    
def home(request):

    return render(request, 'bases/index.html')

app/templates/app/blog_list.html
{% extends 'bases/index.html' %}

{% block slider %} {% endblock slider %}

{% block contenido %}

<body class="stretched">

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Blog</h1>
				<span>Más Recientes</span>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url 'bases:home' %}">Inicio</a></li>
					<li class="breadcrumb-item active" aria-current="page">Blog</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="row gutter-40 col-mb-80">
						<!-- Post Content
						============================================= -->
						<div class="postcontent col-lg-9">

							<!-- Posts
							============================================= -->
							<div id="posts" class="row grid-container gutter-30">

								<div class="entry col-12">
									<div class="grid-inner">
										<div class="entry-image">
											<a href="/static/base/images/blog/full/avivabajio.jpeg" data-lightbox="image"><img src="/static/base/images/blog/full/avivabajio.jpeg" alt="Standard Post with Image"></a>
										</div>
										<div class="entry-title">
											<h2><a href="{% url 'app:blog' %}">AVIVABAJÍO KIDS</a></h2>
										</div>
										<div class="entry-meta">
											<ul>
												<li><i class="icon-calendar3"></i> 10th February 2021</li>
												<li><a href="#"><i class="icon-user"></i> admin</a></li>
												<!-- <li><i class="icon-folder-open"></i> <a href="#">General</a>, <a href="#">Media</a></li> -->
												<li><a href="blog-single.html#comments"><i class="icon-comments"></i> 13 Comentarios</a></li>
												<!-- <li><a href="#"><i class="icon-camera-retro"></i></a></li> -->
											</ul>
										</div>
										<div class="entry-content">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, asperiores quod est tenetur in. Eligendi, deserunt, blanditiis est quisquam doloribus voluptate id aperiam ea ipsum magni aut perspiciatis rem voluptatibus officia eos rerum deleniti quae nihil facilis repellat atque vitae voluptatem libero at eveniet veritatis ab facere.</p>
											<a href="blog-single.html" class="more-link">Seguir leyendo</a>
										</div>
									</div>
								</div>



								<div class="entry col-12">
									<div class="grid-inner">
										<div class="entry-image">
											<a href="/static/base/images/blog/full/devocional.jpeg" data-lightbox="image"><img src="/static/base/images/blog/full/devocional.jpeg" alt="Standard Post with Image"></a>
										</div>
										<div class="entry-title">
											<h2><a href="{% url 'app:blog' %}">DEVOCIONAL DIARIO</a></h2>
										</div>
										<div class="entry-meta">
											<ul>
												<li><i class="icon-calendar3"></i> 10th February 2021</li>
												<li><a href="#"><i class="icon-user"></i> admin</a></li>
												<!-- <li><i class="icon-folder-open"></i> <a href="#">General</a>, <a href="#">Media</a></li> -->
												<li><a href="blog-single.html#comments"><i class="icon-comments"></i> 13 Comentarios</a></li>
												<!-- <li><a href="#"><i class="icon-camera-retro"></i></a></li> -->
											</ul>
										</div>
										<div class="entry-content">
											<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, asperiores quod est tenetur in. Eligendi, deserunt, blanditiis est quisquam doloribus voluptate id aperiam ea ipsum magni aut perspiciatis rem voluptatibus officia eos rerum deleniti quae nihil facilis repellat atque vitae voluptatem libero at eveniet veritatis ab facere.</p>
											<a href="blog-single.html" class="more-link">Seguir leyendo</a>
										</div>
									</div>
								</div>



							</div><!-- #posts end -->

							<!-- Pager
							============================================= -->
							<div class="d-flex justify-content-between mt-5">
								<a href="#" class="btn btn-outline-secondary">&larr; Anterior</a>
								<a href="#" class="btn btn-outline-dark">Siguiente &rarr;</a>
							</div>
							<!-- .pager end -->

						</div><!-- .postcontent end -->

						<!-- Sidebar
						============================================= -->
						<div class="sidebar col-lg-3">
							<div class="sidebar-widgets-wrap">

								<!-- <div class="widget widget-twitter-feed clearfix">

									<h4>Twitter Feed</h4>
									<ul class="iconlist twitter-feed" data-username="envato" data-count="2">
										<li></li>
									</ul>

									<a href="#" class="btn btn-secondary btn-sm float-end">Follow Us on Twitter</a>

								</div> -->

								<!-- <div class="widget clearfix">

									<h4>Flickr Photostream</h4>
									<div id="flickr-widget" class="flickr-feed masonry-thumbs grid-container" data-id="613394@N22" data-count="16" data-type="group" data-lightbox="gallery"></div>

								</div> -->

								<div class="widget clearfix">

									<div class="tabs mb-0 clearfix" id="sidebar-tabs">

										<ul class="tab-nav clearfix">
											<li><a href="#tabs-1">Popular</a></li>
											<li><a href="#tabs-2">Reciente</a></li>
											<li><a href="#tabs-3"><i class="icon-comments-alt me-0"></i></a></li>
										</ul>

										<div class="tab-container">

											<div class="tab-content clearfix" id="tabs-1">
												<div class="posts-sm row col-mb-30" id="popular-post-list-sidebar">
													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/3.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Lorem ipsum dolor sit amet, consectetur</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li><i class="icon-comments-alt"></i> 35 Comments</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/2.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Elit Assumenda vel amet dolorum quasi</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li><i class="icon-comments-alt"></i> 24 Comments</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/1.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Debitis nihil placeat, illum est nisi</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li><i class="icon-comments-alt"></i> 19 Comments</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="tab-content clearfix" id="tabs-2">
												<div class="posts-sm row col-mb-30" id="recent-post-list-sidebar">
													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/1.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Lorem ipsum dolor sit amet, consectetur</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li>10th July 2021</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/2.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Elit Assumenda vel amet dolorum quasi</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li>10th July 2021</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/magazine/small/3.jpg" alt="Image"></a>
																</div>
															</div>
															<div class="col ps-3">
																<div class="entry-title">
																	<h4><a href="#">Debitis nihil placeat, illum est nisi</a></h4>
																</div>
																<div class="entry-meta">
																	<ul>
																		<li>10th July 2021</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="tab-content clearfix" id="tabs-3">
												<div class="posts-sm row col-mb-30" id="recent-comments-list-sidebar">
													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/icons/avatar.jpg" alt="User Avatar"></a>
																</div>
															</div>
															<div class="col ps-3">
																<strong>John Doe:</strong> Veritatis recusandae sunt repellat distinctio...
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/icons/avatar.jpg" alt="User Avatar"></a>
																</div>
															</div>
															<div class="col ps-3">
																<strong>Mary Jane:</strong> Possimus libero, earum officia architecto maiores....
															</div>
														</div>
													</div>

													<div class="entry col-12">
														<div class="grid-inner row g-0">
															<div class="col-auto">
																<div class="entry-image">
																	<a href="#"><img class="rounded-circle" src="images/icons/avatar.jpg" alt="User Avatar"></a>
																</div>
															</div>
															<div class="col ps-3">
																<strong>Site Admin:</strong> Deleniti magni labore laboriosam odio...
															</div>
														</div>
													</div>
												</div>
											</div>

										</div>

									</div>

								</div>



							</div>

						</div><!-- .sidebar end -->
					</div>

				</div>
			</div>
		</section><!-- #content end -->

	</div><!-- #wrapper end -->

	{% endblock contenido %}



</body>
</html>

app/templates/app/conferencia.html
{% extends 'bases/index.html' %}

{% block slider %} {% endblock slider %}

{% block contenido %}

<body class="stretched">

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Page Title
		============================================= -->

		<!-- Content
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Conferencia</h1>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url 'bases:home' %}">Inicio</a></li>
					<li class="breadcrumb-item"><a href="{% url 'app:conferencias' %}">Conferencias</a></li>
					<li class="breadcrumb-item active" aria-current="page">Conferencia</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="single-post mb-0">

						<!-- Single Post
						============================================= -->
						<div class="entry clearfix">

							<!-- Entry Title
							============================================= -->
							<div class="entry-title">
								<h2>This is a Standard post with a Preview Image</h2>
							</div><!-- .entry-title end -->

							<!-- Entry Meta
							============================================= -->
							<div class="entry-meta">
								<ul>
									<li><i class="icon-calendar3"></i> 10 de Julio del 2021</li>
									<li><a href="#"><i class="icon-user"></i> admin</a></li>
									<!-- <li><i class="icon-folder-open"></i> <a href="#">General</a>, <a href="#">Media</a></li> -->
									<li><a href="#"><i class="icon-comments"></i> 43 Comentarios</a></li>
									<!-- <li><a href="#"><i class="icon-camera-retro"></i></a></li> -->
								</ul>
							</div><!-- .entry-meta end -->

							<!-- Entry Image
							============================================= -->
							<div class="entry-image bottommargin">
								<a href="#"><img src="/static/base/images/slider/swiper/1.jpg" alt="Blog Single"></a>
							</div><!-- .entry-image end -->

							<!-- Entry Content
							============================================= -->
							<div class="entry-content mt-0">

								<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>

								<p>Nullam id dolor id nibh ultricies vehicula ut id elit. <a href="#">Curabitur blandit tempus porttitor</a>. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis euismod semper.</p>

								<blockquote><p>Vestibulum id ligula porta felis euismod semper. Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.</p></blockquote>

								<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras mattis consectetur purus sit amet fermentum. Donec id elit non mi porta gravida at eget metus.</p>

								<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Aenean lacinia bibendum nulla sed consectetur. Cras justo odio, dapibus ac facilisis in, egestas eget quam. <a href="#">Nullam quis risus eget urna</a> mollis ornare vel eu leo. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>

		<pre>
		#header-inner {
		width: 940px;
		margin: 0 auto;
		padding-top: 40px;
		}</pre>

								<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>

								<p>Nullam id dolor id nibh ultricies vehicula ut id elit. Curabitur blandit tempus porttitor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis euismod semper.</p>
								<!-- Post Single - Content End -->



								<div class="clear"></div>

								<!-- Post Single - Share
								============================================= -->
								<div class="si-share border-0 d-flex justify-content-between align-items-center">
									<span>Compartir Este Post:</span>
									<div>
										<a href="#" class="social-icon si-borderless si-facebook">
											<i class="icon-facebook"></i>
											<i class="icon-facebook"></i>
										</a>
										<a href="#" class="social-icon si-borderless si-twitter">
											<i class="icon-twitter"></i>
											<i class="icon-twitter"></i>
										</a>
										<a href="#" class="social-icon si-borderless si-instagram">
											<i class="icon-instagram"></i>
											<i class="icon-instagram"></i>
										</a>

									</div>
								</div><!-- Post Single - Share End -->

							</div>
						</div><!-- .entry end -->

						<!-- Post Navigation
						============================================= -->
						<div class="row justify-content-between col-mb-30 post-navigation">
							<div class="col-12 col-md-auto text-center">
								<a href="#">&lArr; Anterior</a>
							</div>

							<div class="col-12 col-md-auto text-center">
								<a href="#">Siguiente &rArr;</a>
							</div>
						</div><!-- .post-navigation end -->

						<div class="line"></div>


						<!-- Comments
						============================================= -->
						<div id="comments" class="clearfix">

							<h3 id="comments-title"><span>3</span> Comentarios</h3>

							<!-- Comments List
							============================================= -->
							<ol class="commentlist clearfix">

								<li class="comment even thread-even depth-1" id="li-comment-1">

									<div id="comment-1" class="comment-wrap clearfix">

										<div class="comment-meta">

											<div class="comment-author vcard">

												<span class="comment-avatar clearfix">
												<img alt='Image' src='https://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=60' class='avatar avatar-60 photo avatar-default' height='60' width='60' /></span>

											</div>

										</div>

										<div class="comment-content clearfix">

											<div class="comment-author">John Doe<span><a href="#" title="Permalink to this comment">April 24, 2012 at 10:46 am</a></span></div>

											<p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>

											<a class='comment-reply-link' href='#'><i class="icon-reply"></i></a>

										</div>

										<div class="clear"></div>

									</div>


									<ul class='children'>

										<li class="comment byuser comment-author-_smcl_admin odd alt depth-2" id="li-comment-3">

											<div id="comment-3" class="comment-wrap clearfix">

												<div class="comment-meta">

													<div class="comment-author vcard">

														<span class="comment-avatar clearfix">
														<img alt='Image' src='https://1.gravatar.com/avatar/30110f1f3a4238c619bcceb10f4c4484?s=40&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D40&amp;r=G' class='avatar avatar-40 photo' height='40' width='40' /></span>

													</div>

												</div>

												<div class="comment-content clearfix">

													<div class="comment-author"><a href='#' rel='external nofollow' class='url'>SemiColon</a><span><a href="#" title="Permalink to this comment">April 25, 2012 at 1:03 am</a></span></div>

													<p>Nullam id dolor id nibh ultricies vehicula ut id elit.</p>

													<a class='comment-reply-link' href='#'><i class="icon-reply"></i></a>

												</div>

												<div class="clear"></div>

											</div>

										</li>

									</ul>

								</li>

								<li class="comment byuser comment-author-_smcl_admin even thread-odd thread-alt depth-1" id="li-comment-2">

									<div id="comment-2" class="comment-wrap clearfix">

										<div class="comment-meta">

											<div class="comment-author vcard">

												<span class="comment-avatar clearfix">
												<img alt='Image' src='https://1.gravatar.com/avatar/30110f1f3a4238c619bcceb10f4c4484?s=60&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D60&amp;r=G' class='avatar avatar-60 photo' height='60' width='60' /></span>

											</div>

										</div>

										<div class="comment-content clearfix">

											<div class="comment-author"><a href='https://themeforest.net/user/semicolonweb' rel='external nofollow' class='url'>SemiColon</a><span><a href="#" title="Permalink to this comment">April 25, 2012 at 1:03 am</a></span></div>

											<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>

											<a class='comment-reply-link' href='#'><i class="icon-reply"></i></a>

										</div>

										<div class="clear"></div>

									</div>

								</li>

							</ol><!-- .commentlist end -->

							<div class="clear"></div>

							<!-- Comment Form
							============================================= -->
							<div id="respond">

								<h3>DEJA UN <span>COMENTARIO</span></h3>

								<form class="row" action="#" method="post" id="commentform">
									<div class="col-md-4 form-group">
										<label for="author">Nombre: </label>
										<input type="text" name="author" id="author" value="" size="22" tabindex="1" class="sm-form-control" />
									</div>

									<div class="col-md-4 form-group">
										<label for="email">Correo: </label>
										<input type="text" name="email" id="email" value="" size="22" tabindex="2" class="sm-form-control" />
									</div>

									<div class="w-100"></div>

									<div class="col-12 form-group">
										<label for="comment">Comentario</label>
										<textarea name="comment" cols="58" rows="7" tabindex="4" class="sm-form-control"></textarea>
									</div>

									<div class="col-12 form-group">
										<button name="submit" type="submit" id="submit-button" tabindex="5" value="Submit" class="button button-3d m-0">Publicar</button>
									</div>
								</form>

							</div><!-- #respond end -->

						</div><!-- #comments end -->

					</div>

				</div>
			</div>
		</section>

		{% endblock contenido %}

</body>

app/templates/app/conferencias_list.html
{% extends 'bases/index.html' %}

{% block slider %} {% endblock slider %}

{% block contenido %}
		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Conferencias</h1>
				<span>Más recientes</span>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url 'bases:home' %}">Inicio</a></li>
					<li class="breadcrumb-item active" aria-current="page">Conferencias</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<!-- Posts
					============================================= -->
					<div id="posts" class="row grid-container gutter-30">

						<div class="entry col-12">
							<div class="grid-inner">
								<div class="entry-image">
									<a href="/static/base/images/slider/swiper/1.jpg" data-lightbox="image"><img src="/static/base/images/slider/swiper/1.jpg" alt="Standard Post with Image"></a>
								</div>
								<div class="entry-title">
									<h2><a href="{% url 'app:conferencia_view' %}">SACA EL DAVID QUE LLEVAS DENTRO</a></h2>
								</div>
								<div class="entry-meta">
									<ul>
										<li><i class="icon-calendar3"></i> 10 de Julio del 2021</li>
										<li><a href="#"><i class="icon-user"></i> admin</a></li>
										<!-- <li><i class="icon-folder-open"></i> <a href="#">General</a>, <a href="#">Media</a></li> -->
										<li><a href="blog-single.html#comments"><i class="icon-comments"></i> 13 Comentarios</a></li>
										<!-- <li><a href="#"><i class="icon-camera-retro"></i></a></li> -->
									</ul>
								</div>
								<div class="entry-content">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, asperiores quod est tenetur in. Eligendi, deserunt, blanditiis est quisquam doloribus voluptate id aperiam ea ipsum magni aut perspiciatis rem voluptatibus officia eos rerum deleniti quae nihil facilis repellat atque vitae voluptatem libero at eveniet veritatis ab facere.</p>
									<a href="{% url 'app:conferencia_view' %}" class="more-link">Seguir leyendo</a>
								</div>
							</div>
						</div>

						<div class="entry col-12">
							<div class="grid-inner">
								<div class="entry-image">
									<a href="/static/base/images/slider/swiper/portada.jpg" data-lightbox="image"><img src="/static/base/images/slider/swiper/portada.jpg" alt="Standard Post with Image"></a>
								</div>
								<div class="entry-title">
									<h2><a href="{% url 'app:conferencia_view' %}">UNCIÓN, FE Y COMPROMISO</a></h2>
								</div>
								<div class="entry-meta">
									<ul>
										<li><i class="icon-calendar3"></i> 10 de Julio del 2021</li>
										<li><a href="#"><i class="icon-user"></i> admin</a></li>
										<!-- <li><i class="icon-folder-open"></i> <a href="#">General</a>, <a href="#">Media</a></li> -->
										<li><a href="blog-single.html#comments"><i class="icon-comments"></i> 13 Comentarios</a></li>
										<!-- <li><a href="#"><i class="icon-camera-retro"></i></a></li> -->
									</ul>
								</div>
								<div class="entry-content">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, asperiores quod est tenetur in. Eligendi, deserunt, blanditiis est quisquam doloribus voluptate id aperiam ea ipsum magni aut perspiciatis rem voluptatibus officia eos rerum deleniti quae nihil facilis repellat atque vitae voluptatem libero at eveniet veritatis ab facere.</p>
									<a href="{% url 'app:conferencia_view' %}" class="more-link">Seguir leyendo</a>
								</div>
							</div>
						</div>

					</div><!-- #posts end -->

					<!-- Pager
					============================================= -->
					<div class="d-flex justify-content-between mt-5">
						<a href="#" class="btn btn-outline-secondary">&larr; Anterior</a>
						<a href="#" class="btn btn-outline-dark">Siguiente &rarr;</a>
					</div>
					<!-- .pager end -->

				</div>
			</div>
		</section><!-- #content end -->

		{% endblock contenido %}


</body>
</html>

bases/templates/bases/index.html
{% extends 'bases/index.html' %}